### ISSUE TITLE
how to deal with the abnormal processes such as exception, if-else branches?

### ISSUE THREAD

**Issue by jiajianrong** [hauld/matiq#1]
Your example is great. So the real case is complicate, for example, we want to add the feature:
if the birthday-party person is nearby our company, say 50 miles, we want to send the extra coupon within the mail.

How does the SEQUENCE FLOW handle this case? A if-else clause in the run function is not wanted, because it breaks the event process. Thanks.

`
function sendDiscounts(id){
        const run = (runner) => {
            // user found from previous task
            let input = runner.getInput();
            // mock logic of sending email
            console.log('Discount sent to', input['find_users'].users);
            // notify task done
            runner.doneTask();
        }
        
        return TASK(id, run)
    }
`

**Comment by hauld** [comment]
Hello, the if-else for flow branching isn't implemented. You might add extra logic to the run task to realize the complex business needs.
